name: Dump database
on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: 0,5,10,15,20,25,30,35,40,45,50,55  * * * *
jobs:
  dump:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: mongo-clone-action
        run: |
          mongodump "mongodb+srv://${{secrets.MONGODB_USERNAME}}:${{secrets.MONGODB_PASSWORD}}@amonitoj-main.szbedsg.mongodb.net/"
