name: Dump database
on:
  schedule:
    - cron: 0,5,10,15,20,25,30,35,40,45,50,55  * * * *
jobs:
  dump:
    runs-on: ubuntu-18.04
    steps:
      - name: download tool
        run: |
          wget https://fastdl.mongodb.org/tools/db/mongodb-database-tools-ubuntu1804-x86_64-100.6.0.tgz
          tar -zxvf mongodb-database-tools-ubuntu1804-x86_64-100.6.0.tgz
          cd mongodb-database-tools-ubuntu1804-x86_64-100.6.0/bin
          ls
