name: Dump database
on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: 0,5,10,15,20,25,30,35,40,45,50,55  * * * *
jobs:
  dump:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.4.2
      - run: |
          rm -rf dump
          mongodump "mongodb+srv://${{secrets.MONGODB_USERNAME}}:${{secrets.MONGODB_PASSWORD}}@amonitoj-main.szbedsg.mongodb.net/"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "sync database"
          git push
