name: Dump database
on:
  push:
    paths:
      - '**.yml'
  schedule:
    - cron: 57 * * * *
jobs:
  dump:
    runs-on: ubuntu-20.04
    steps:
      - name: clone
        uses: actions/checkout@v2.4.2
      - name: dump data
        run: |
          rm -rf dump
          mongodump "mongodb+srv://${{secrets.MONGODB_USERNAME}}:${{secrets.MONGODB_PASSWORD}}@${{secrets.MONGODB_URL}}/"
          echo Sync MongoDB data at $(date). >README.md
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "sync database"
          git push
