name: Dump database
on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: 50 * * * *
jobs:
  dump:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.4.2
      - run: |
          rm -rf dump
          mongodump "mongodb+srv://${{secrets.MONGODB_USERNAME}}:${{secrets.MONGODB_PASSWORD}}@${{secrets.MONGODB_URL}}"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "sync database"
          git push
